### ISSUE TITLE
似乎会直接删除原有的 username.github.io ？

### ISSUE THREAD

**Issue by YCF** [Bitmoe/PortableHexo#1]
差点丢了数据。

**Comment by ghost** [comment]
我们会处理的。谢谢您的反馈

**Comment by qistchan** [comment]
@YCF  如果你是用来当做 便携版使用：
1. 请先将原来的hexo文件夹里的 source、themes、_config.yml（如果是ssh修改成https）替换掉便携版里面的对应文件
2. 运行`启动命令行.bat
3. 手动执行：
   
   · git config --global credential.helper store
   
   · git config --global user.name 用户名
   
   · git config --global user.email 邮箱
4. 就不需要执行 `配置Github部署.bat & 配置基本信息.bat`了，其余的批处理文件可以直接使用的。

**Comment by YCF** [comment]
幸好我的博客是写在issue上的，不然，真的都丢了！（虽然都没什么价值）

**Comment by ghw** [comment]
实在抱歉，没有事先声明，下次更新时会添上，感谢您的反馈。
