### ISSUE TITLE
还是没有办法使用啊~~

### ISSUE THREAD

**Issue by hiarno** [Bitmoe/PortableHexo#2]
还是没有办法使用啊~~

**Comment by hiarno** [comment]
提示没有找到git-bash

**Comment by qistchan** [comment]
解压之后你的文件结构是怎样的~？

**Comment by hiarno** [comment]
如图所示，换了多台电脑都是同样的情况。

路径都是"D:\Program Files\PortableHexo"，注意”Program Files“有空格。

测了3台WIN10的电脑都不行。

有的安装过Git Bash，有的是新系统。

![001.jpg](https://ooo.0o0.ooo/2016/05/11/5732eab13d20b.jpg)

**Comment by qistchan** [comment]
能否尝试在 路径中不带空格 的位置运行？

**Comment by hiarno** [comment]
确认的有电晚哈，是空格的问题。
另外使用这个软件，会清空原来的博客。。。

**Comment by ghw** [comment]
您好，新创建或.deploy_git被清空的情况下，HEXO会强制push，这会导致老的记录被覆盖
