### ISSUE TITLE
我的建议

### ISSUE THREAD

**Issue by 0xMashiro** [Bitmoe/PortableHexo#6]
配置Git的时候脚本，针对二次使用可以写的具体一点（加步骤）：
因为今天我用这个的时候它居然把我原有数据全部清空了，这损失太大了。
是否已经在github上使用hexo搭建过博客？
yes no
if yes
请输入你的page分支名字（默认master）：
name
然后就git操作clone下来，因为新手是不了解clone，更不知道reset的。

以上建议仅供参考，希望有所帮助。

**Comment by ghw** [comment]
感谢您的建议，下一个版本会添加进去（我们在重新梳理便携版本代码，这个需要一点时间）
