### ISSUE TITLE
安装成功，但是没有发现换主题的功能。

### ISSUE THREAD

**Issue by GuoRan18** [Bitmoe/PortableHexo#8]
安装成功，但是没有发现换主题的功能。

**Comment by ghw** [comment]
需要手动更换的，把主题下载到themes目录，然后修改下hexo目录的_config.yml配置文件，hexo clean;hexo d

**Comment by GuoRan18** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
这个道理我懂，现在有个问题是下载是通过“启动命令行.bat”这里面下载吧？ 但是我在命令 git clone git@github.com:forsigner/fexo.git themes/fexo  下载主题的时候提示我Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. 请教这是怎么回事？



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
一半是春夏，一半是秋冬。


                


    在2018年4月4日 11:16，Haowu Ge<notifications@github.com> 写道： 


需要手动更换的，把主题下载到themes目录，然后修改下hexo目录的_config.yml配置文件，hexo clean;hexo d

**Comment by xCss** [comment]
命令行改成 `git clone https://github.com/forsigner/fexo.git themes/fexo `
或者[手动下载zip包](https://github.com/forsigner/fexo/archive/master.zip)自己解压

**Comment by GuoRan18** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
我试试，谢谢了。



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
一半是春夏，一半是秋冬。


                


    在2018年4月4日 11:44，Nine<notifications@github.com> 写道： 


命令行改成 git clone https://github.com/forsigner/fexo.git themes/fexo 
或者手动下载zip包自己解压
